version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_ACCESS_PRIVATE_KEY=${JWT_ACCESS_PRIVATE_KEY}
      - JWT_REFRESH_PRIVATE_KEY=${JWT_REFRESH_PRIVATE_KEY}
      - EMAIL_PROVIDER=${EMAIL_PROVIDER}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
    restart: unless-stopped
